version: '3'

services:
  web: &web
    environment:
      - DB_NAME=weather_app_db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - API_KEY=b859a7d902ad915b8fa75c313144a0d2
      - DJANGO_SETTINGS_MODULE=main.settings.ci
    build: .
    volumes:
      - .:/code
    ports:
      - "3456:80"
    restart: "always"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=weather_app_db
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: "always"