version: '3'

services:
  web: &web
    environment:
      - DB_NAME=weather_app_db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - API_KEY=<YOUR API KEY>
      - DJANGO_SETTINGS_MODULE=main.settings.prod
    build: .
    volumes:
      - .:/code
    ports:
      - "3456:3456"
    restart: "always"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=weather_app_db
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: "always"